### ISSUE TITLE
Authentication Error [Username, password] are no longer accepted

### ISSUE THREAD

**Issue by haithambassam** [RedMadRobot/fastlane-plugin-gmail#6]
The plugin now does not work maybe due to new security updates.

7.8 **Username and Password not accepted. Learn more at (Net::SMTPAuthenticationError)**

**Comment by Alexander-Ignition** [comment]
Hello, @haithambassam 

I checked my mail sending. This error **Username and Password not accepted. Learn more at (Net::SMTPAuthenticationError)** was when I entered the password from my mail.

When I created and entered the password for the application, the email was successfully sent.

Please double-check which email password you are entering
You may need to create and use a password for the application
[Sign in using App Passwords](https://support.google.com/accounts/answer/185833?hl=en)

**Comment by haithambassam** [comment]
Thanks, app passwords have worked
