### ISSUE TITLE
Send Emails using other domains than Gmail

### ISSUE THREAD

**Issue by haithambassam** [RedMadRobot/fastlane-plugin-gmail#7]
Can this plugin be used to send emails from another Domains like outlook, or even specific company domains?

**Comment by Alexander-Ignition** [comment]
Hello @haithambassam 

In this plugin, the gmail address and port are hardcoded

Sorry, the plugin will not be able to send an email to other mail servers.

**Comment by haithambassam** [comment]
Thanks.
